### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by esenpillai** [urasandesu/Prig#74] opened 2016-08-12 18:29 UTC
I have visual studio installed on my D drive. When I try to register prig it says unable to run testwindow because it is trying to locate commonextensions folder under c drive.

**Comment by urasandesu** [comment] 2016-08-13 01:17
Thank you for the reporting!

I didn't have tested in the environment like yours, sorry... I found the cause is that [MachineWideInstaller](https://github.com/urasandesu/Prig/blob/518dd42200a5fd14c14112ceaa838eec9171f9d2/Urasandesu.Prig.VSPackage/Models/MachineWideInstaller.cs#L170) uses `C:\Program Files` as a fixed value. I think that the method can specify the location by [the algorithm same as Prig Assembly addition process](https://github.com/urasandesu/Prig/blob/778e16f3de50f52abb1df478a60fa48aa6ae7fea/Urasandesu.Prig.VSPackage/tools/Add-PrigAssembly.ps1#L163) -- it uses the environment variable matching to `VS\d{3}COMNTOOLS`, so this issue will be fixed until next release.

For your information, you can manually install that by the following steps: 

1. In Visual Studio, choose `PRIG` - `Register Prig (Needs Restarting)` menu(the error will occur).
2. In Developer Command Prompt for VS2013 as Administrator, execute [`prig install` command](https://github.com/urasandesu/Prig/wiki/Command-Line-Reference#-installer-options).
3. Restart Visual Studio.

Probably, you have to execute the command like this because you installed Visual Studio in `D` drive: 
```dos
CMD C:\> prig install TestWindow_for_d_drive -source "D:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
CMD C:\> prig install TestWindow1_for_d_drive -source "D:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\x64"
```

If you are in haste, please try them.

**Closed** 2016-08-13 11:52 UTC
Labels: bug

**Comment by esenpillai** [comment] 2016-08-13 13:04
Thank you this work around solved my issue
