### ISSUE TITLE
Unit tests on specific class repeatedly crashes ms test runner

### ISSUE THREAD

**Issue by wegged** [urasandesu/Prig#32] opened 2015-04-03 05:33 UTC
We have an older service we had some unit tests with ms fake that worked that we are trying to convert the test to prig but it crashes vstest.executionengine. what is the best way to debug the issue?  

The issue is reproducible every time with this class (it has some static properties/fields that we are trying to mock out but for the sake of argument I set these all to null in the System Under Test and did not stub any methods but it still crashes when running any test (even just new Service()) with the prig test adapter is enabled.  

Here is information from the dump.

Dump Summary
------------
Dump File:	vstest.executionengine.exe.26884.dmp : C:\Users\wege\AppData\Local\CrashDumps\vstest.executionengine.exe.26884.dmp
Last Write Time:	4/3/2015 12:26:03 AM
Process Name:	vstest.executionengine.exe : C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\Common7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe
Process Architecture:	x64
Exception Code:	0xC0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Heap Information:	Present

System Information
------------------
OS Version:	6.1.7601
CLR Version(s):	4.5.27.0

Modules
-------
Module Name	Module Path	Module Version
-----------	-----------	--------------
vstest.executionengine.exe	C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 12.0\Common7\IDE\COMMONEXTENSIONS\MICROSOFT\TESTWINDOW\vstest.executionengine.exe	12.0.30501.0
ntdll.dll	C:\Windows\System32\ntdll.dll	6.1.7601.18247
mscoree.dll	C:\Windows\System32\mscoree.dll	4.0.40305.0
kernel32.dll	C:\Windows\System32\kernel32.dll	6.1.7601.18409
KERNELBASE.dll	C:\Windows\System32\KERNELBASE.dll	6.1.7601.18409
sxwmon64.dll	C:\Windows\System32\sxwmon64.dll	4.5.2710.0
user32.dll	C:\Windows\System32\user32.dll	6.1.7601.17514
gdi32.dll	C:\Windows\System32\gdi32.dll	6.1.7601.18577
lpk.dll	C:\Windows\System32\lpk.dll	6.1.7601.18177
usp10.dll	C:\Windows\System32\usp10.dll	1.626.7601.18454
msvcrt.dll	C:\Windows\System32\msvcrt.dll	7.0.7601.17744
advapi32.dll	C:\Windows\System32\advapi32.dll	6.1.7601.18247
sechost.dll	C:\Windows\System32\sechost.dll	6.1.7600.16385
rpcrt4.dll	C:\Windows\System32\rpcrt4.dll	6.1.7601.18532
shell32.dll	C:\Windows\System32\shell32.dll	6.1.7601.18429
shlwapi.dll	C:\Windows\System32\shlwapi.dll	6.1.7601.17514
ole32.dll	C:\Windows\System32\ole32.dll	6.1.7601.17514
oleaut32.dll	C:\Windows\System32\oleaut32.dll	6.1.7601.18640
imm32.dll	C:\Windows\System32\imm32.dll	6.1.7600.16385
msctf.dll	C:\Windows\System32\msctf.dll	6.1.7600.16385
DAinit.dll	C:\Windows\System32\DAinit.dll	7.0.0.36
vmwsci.dll	C:\Windows\System32\vmwsci.dll	5.3.2.24325
psapi.dll	C:\Windows\System32\psapi.dll	6.1.7600.16385
mscoreei.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll	4.5.27.0
clr.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll	4.5.27.0
MSVCR120_CLR0400.dll	C:\Windows\System32\MSVCR120_CLR0400.dll	12.0.52242.36242
Urasandesu.Prig.dll	C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha03\tools\x64\Urasandesu.Prig.dll	0.1.0.0
dbghelp.dll	C:\Windows\System32\dbghelp.dll	6.1.7601.17514
msvcp120.dll	C:\Windows\System32\msvcp120.dll	12.0.21005.1
msvcr120.dll	C:\Windows\System32\msvcr120.dll	12.0.21005.1
version.dll	C:\Windows\System32\version.dll	6.1.7600.16385
fusion.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\fusion.dll	4.5.27.0
cryptsp.dll	C:\Windows\System32\cryptsp.dll	6.1.7600.16385
rsaenh.dll	C:\Windows\System32\rsaenh.dll	6.1.7600.16385
CRYPTBASE.dll	C:\Windows\System32\CRYPTBASE.dll	6.1.7600.16385
clrjit.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clrjit.dll	4.5.27.0
nlssorting.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\nlssorting.dll	4.5.27.0
System.Transactions.dll	C:\Windows\Microsoft.Net\assembly\GAC_64\System.Transactions\v4.0_4.0.0.0__b77a5c561934e089\System.Transactions.dll	4.5.27.0
pcwum.dll	C:\Windows\System32\pcwum.dll	6.1.7600.16385
bcrypt.dll	C:\Windows\System32\bcrypt.dll	6.1.7600.16385
secur32.dll	C:\Windows\System32\secur32.dll	6.1.7601.18779
sspicli.dll	C:\Windows\System32\sspicli.dll	6.1.7601.18779
credssp.dll	C:\Windows\System32\credssp.dll	6.1.7601.18779
msv1_0.dll	C:\Windows\System32\msv1_0.dll	6.1.7601.18779
cryptdll.dll	C:\Windows\System32\cryptdll.dll	6.1.7600.16385
System.Data.dll	C:\Windows\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll	4.5.27.0
ws2_32.dll	C:\Windows\System32\ws2_32.dll	6.1.7601.17514
nsi.dll	C:\Windows\System32\nsi.dll	6.1.7600.16385
crypt32.dll	C:\Windows\System32\crypt32.dll	6.1.7601.18277
msasn1.dll	C:\Windows\System32\msasn1.dll	6.1.7601.17514
diasymreader.dll	C:\Windows\Microsoft.NET\Framework64\v4.0.30319\diasymreader.dll	12.0.52242.36242
RpcRtRemote.dll	C:\Windows\System32\RpcRtRemote.dll	6.1.7601.17514
clbcatq.dll	C:\Windows\System32\clbcatq.dll	2001.12.8530.16385
uxtheme.dll	C:\Windows\System32\uxtheme.dll	6.1.7600.16385
urlmon.dll	C:\Windows\System32\urlmon.dll	11.0.9600.17496
api-ms-win-downlevel-ole32-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-ole32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-shlwapi-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-shlwapi-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-advapi32-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-advapi32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-user32-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-user32-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-version-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-version-l1-1-0.dll	6.2.9200.16492
api-ms-win-downlevel-normaliz-l1-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-normaliz-l1-1-0.dll	6.2.9200.16492
normaliz.dll	C:\Windows\System32\normaliz.dll	6.1.7600.16385
iertutil.dll	C:\Windows\System32\iertutil.dll	11.0.9600.17496
wininet.dll	C:\Windows\System32\wininet.dll	11.0.9600.17496
userenv.dll	C:\Windows\System32\userenv.dll	6.1.7601.17514
profapi.dll	C:\Windows\System32\profapi.dll	6.1.7600.16385
api-ms-win-downlevel-advapi32-l2-1-0.dll	C:\Windows\System32\api-ms-win-downlevel-advapi32-l2-1-0.dll	6.2.9200.16492

**Comment by urasandesu** [comment] 2015-04-04 01:21
It maybe seems same cause to #33. Could you download [my latest local build *.nupkg](https://drive.google.com/open?id=0B4s_gXgDJAgbRFhDaDl1NHNxWkU&authuser=0) and try the following steps?

1. Install the above package.
2. Unregister the Prig framework assemblies from GAC(execute `gacutil /u "Urasandesu.Prig.Framework, Version=0.1.0.0, Culture=neutral, PublicKeyToken=acabb3ef0ebf69ce, processorArchitecture=MSIL"` and `gacutil /u "Urasandesu.NAnonym, Version=0.2.0.0, Culture=neutral, PublicKeyToken=ce9e95b04334d5fb, processorArchitecture=MSIL"` from Developer Command Prompt for VS2013 as Administrator)
3. Rebuild your test project.
4. Copy the Prig framework assemblies to your test solution directory. For example, if your test solution is located at `C:\Users\Wegged\Documents\Visual Studio 2013\Projects\YourTest\YourTest.sln`, copy the assemblies like `C:\Users\Wegged\Documents\Visual Studio 2013\Projects\YourTest\Urasandesu.NAnonym.dll` and `C:\Users\Wegged\Documents\Visual Studio 2013\Projects\YourTest\Urasandesu.Prig.Framework.dll`.
5. Copy the Prig framework assemblies to the directory that is same to test execution engine. Usually, it is `C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow`, so copy the assemblies to there like the above step.
6. Execute your tests in Visuatl Studio Test Explorer.

If the internal error gone after the above steps, the cause is probably same as #33.

**Comment by wegged** [comment] 2015-04-07 14:30
Getting an error when trying to install the package am I using the correct command ?

c:\Users\wege\Desktop>choco install Prig.2.0.0-alpha031.nupkg
!!ATTENTION!!
The next version of Chocolatey (v0.9.9) will require -y to perform
  behaviors that change state without prompting for confirmation. Start
  using it now in your automated scripts.

  For details on the all new Chocolatey, visit http://bit.ly/new_choco
Chocolatey (v0.9.8.33) is installing 'Prig.2.0.0-alpha031.nupkg' and dependencie
s. By installing you accept the license for 'Prig.2.0.0-alpha031.nupkg' and each
 dependency you are installing.
Unable to find package 'Prig.2.0.0-alpha031.nupkg'.

Command 'install' failed (sometimes this indicates a partial failure). Additional info/packages: Prig.2.0.0-alpha031.nupkg

**Comment by wegged** [comment] 2015-04-07 20:38
I was able to run from command line and I have the same issues with the new build

**Comment by urasandesu** [comment] 2015-04-08 13:52
Thank you for trying the package!
If it was failed, I have no idea to debug that at the moment :anguished:

By the way, could you tell me the API that triggered the error?

In #33, it was `System.Collections.Generic.List<T>.Add(T)`. If it is possible, I want to try mocking the API that you were going to replace, too.

**Comment by wegged** [comment] 2015-04-08 14:42
Honestly it could be something else my prig setup seems corrupt now lots of things are causing a crash that worked before. I tried to uninstall and reinstall from chocolaty and remove the files I copied over but it seems like its not helping.  

The error occurs even if I am not mocking anything just creating an instance of the class.

**Comment by urasandesu** [comment] 2015-04-09 12:43
In Prig's architecture, the mocking preparation is usually done long before instantiating the target class in user's code. My guess is that the test executor of Visual Studio performs unintended instantiation against the target class in accordance with the indirection setting.

This is a just idea, but you can probably get some different results if deleting the indirection setting in reverse order.

**Comment by wegged** [comment] 2015-04-09 14:41
I get the same result with one indirectionsetting.  Btw I managed to install your package but it seemed to make the issue worst maybe it is the same issue and there is a different regression in the new build.

I did a simple mscorlib test DateTime.Now that worked with the old build which I then uninstalled. Then I installed the new build and followed your instructions but it crashes with the new build.

I tested it with Nunit as well and I get the same behavior. CLR error:80004005

**Comment by wegged** [comment] 2015-04-09 15:19
Ok I take it back the new version works with NUnit for the simple case.  For the case raising the issue before it just hangs.  I do see this in the log folder though perhaps this will shed some light.


","C:\Users\Akira\Prig\Swathe\Urasandesu.Swathe\Urasandesu/Swathe/Profiling/ICorProfilerCallbackImpl.h",274,"long __cdecl CWeaverDetail::CWeaverImpl::JITCompilationStartedCore(unsigned __int64,int)=>Weaver.cpp,393","pModProf.IsPersisted()=>Weaver.cpp,412","!prigData.m_indirectablesInit=>Weaver.cpp,425"
2015/04/09 11:08:34.157604,ERROR,00000x3740,26,0x00003bbc,"        C:\Users\Akira\Prig\Swathe\Urasandesu.Swathe\Urasandesu/Swathe/Metadata/BaseClassPimpl/BaseAssemblyMetadataPimpl.hpp(2125): Throw in function void __cdecl Urasandesu::Swathe::Metadata::BaseClassPimpl::BaseAssemblyMetadataPimpl<struct Urasandesu::Swathe::AutoGen::Metadata::DefaultClassPimplApiHolder::DefaultAssemblyMetadataPimplApiHolder>::ResolveAssemblyPathByCurrentDirectory(const class Urasandesu::Swathe::Metadata::BaseClassPimpl::BaseAssemblyMetadataPimpl<struct Urasandesu::Swathe::AutoGen::Metadata::DefaultClassPimplApiHolder::DefaultAssemblyMetadataPimplApiHolder> *,const class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > &,class boost::filesystem::path &)
Dynamic exception type: class boost::exception_detail::clone_impl<class Urasandesu::CppAnonym::CppAnonymArgumentException>
std::exception::what: The designated assembly is not found: Urasandesu.Prig.Framework
[struct Urasandesu::CppAnonym::tag_stack_trace * __ptr64] = at <Unknown Symbol> in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at TranslateSecurityAttributes in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at CopyPDBs in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InstallCustomModule in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InstallCustomModule in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at <Unknown Symbol> in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at <Unknown Symbol> in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at <Unknown Symbol> in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InstallCustomModule in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at DllGetClassObjectInternal in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InitializeFusion in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at _CorExeMain in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at _CorExeMain in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at _CorExeMain in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at _CorExeMain in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at _CorExeMain in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\mscoreei.dll
at _CorExeMain in C:\Windows\SYSTEM32\MSCOREE.DLL
at BaseThreadInitThunk in C:\Windows\system32\KERNEL32.dll
at RtlUserThreadStart in C:\Windows\SYSTEM32\ntdll.dll

","C:\Users\Akira\Prig\Swathe\Urasandesu.Swathe\Urasandesu/Swathe/Profiling/ICorProfilerCallbackImpl.h",274,"long __cdecl CWeaverDetail::CWeaverImpl::JITCompilationStartedCore(unsigned __int64,int)=>Weaver.cpp,393","pModProf.IsPersisted()=>Weaver.cpp,412","!prigData.m_indirectablesInit=>Weaver.cpp,425"
2015/04/09 11:16:37.773337,ERROR,00000x47ac,18541,0x00003700,"            C:\Users\Akira\Prig\Swathe\Urasandesu.Swathe\Urasandesu/Swathe/Metadata/BaseClassPimpl/BaseInstructionMetadataPimpl.hpp(431): Throw in function unsigned long __cdecl Urasandesu::Swathe::Metadata::BaseClassPimpl::BaseInstructionMetadataPimpl<struct Urasandesu::Swathe::AutoGen::Metadata::DefaultClassPimplApiHolder::DefaultInstructionMetadataPimplApiHolder>::TakeInlineToken(const class Urasandesu::Swathe::Metadata::BaseClassPimpl::BaseInstructionMetadataPimpl<struct Urasandesu::Swathe::AutoGen::Metadata::DefaultClassPimplApiHolder::DefaultInstructionMetadataPimplApiHolder> *,const unsigned char *,const unsigned char *,class boost::variant<struct boost::blank,bool,unsigned char,double,short,int,__int64,struct Urasandesu::Swathe::Metadata::ILocal const *,struct Urasandesu::Swathe::Metadata::Signature const *,struct Urasandesu::Swathe::Metadata::IField const *,struct Urasandesu::Swathe::Metadata::IMethod const *,char,float,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> >,struct Urasandesu::Swathe::Metadata::IType const *,class Urasandesu::Swathe::Metadata::Label,class std::vector<int,class std::allocator<int> >,class std::vector<class Urasandesu::Swathe::Metadata::Label,class std::allocator<class Urasandesu::Swathe::Metadata::Label> >,struct boost::detail::variant::void_,struct boost::detail::variant::void_> &)
Dynamic exception type: class boost::exception_detail::clone_impl<struct Urasandesu::CppAnonym::CppAnonymNotImplementedException>
std::exception::what: mdtTarget: 0x0A00045C
[struct Urasandesu::CppAnonym::tag_stack_trace * __ptr64] = at <Unknown Symbol> in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at DllUnregisterServer in C:\ProgramData\chocolatey\lib\Prig.2.0.0-alpha031\tools\x64\Urasandesu.Prig.dll
at TranslateSecurityAttributes in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at CopyPDBs in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InstallCustomModule in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at InstallCustomModule in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at <Unknown Symbol> in C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
at <Unknown Symbol> in <Unknown Module>
at <Unknown Symbol> in <Unknown Module>
at <Unknown Symbol> in <Unknown Module>
at <Unknown Symbol> in <Unknown Module>
at <Unknown Symbol> in <Unknown Module>
at <Unknown Symbol> in <Unknown Module>

","C:\Users\Akira\Prig\Swathe\Urasandesu.Swathe\Urasandesu/Swathe/Profiling/ICorProfilerCallbackImpl.h",274,"long __cdecl CWeaverDetail::CWeaverImpl::JITCompilationStartedCore(unsigned __int64,int)=>Weaver.cpp,393","pModProf.IsPersisted()=>Weaver.cpp,412","(result = prigData.m_indirectables.find(mdt)) != prigData.m_indirectables.end()=>Weaver.cpp,454","Modifying method=>Weaver.cpp,460"

**Comment by wegged** [comment] 2015-04-09 21:01
sent some details via email by process of elimination I have found at least two methods in my class where if I add settings to stub them I have the hanging/crashing behavior

**Comment by urasandesu** [comment] 2015-04-09 23:49
Thank you for the detailed information! :satisfied:
[The log](https://github.com/urasandesu/Prig/issues/32#issuecomment-91262225) indicates the two errors that have separate causes: 

1. `Urasandesu.Prig.Framework` was not found (occurred at 2015/04/09 11:08:34.157604).
2. Some `MemberRef` token appeared after `ldtoken` opcode in the indirection target method (occurred at 2015/04/09 11:16:37.773337).

About the 1st error, I believe that you have already resolved. Because it is impossible that the 2nd error occurs before the fix in same environment.
About the 2nd error, it is certainly [a bug of the infrastructure](https://github.com/urasandesu/Swathe/issues/1) of Prig.

My guess is the method you e-mailed contains the section that is cause like the 2nd error.

**Comment by wegged** [comment] 2015-04-13 14:45
Would it be possible to get a build with the fix to test this out?

Thanks

**Comment by urasandesu** [comment] 2015-04-13 22:00
Yes, of cource :ok_hand:
My latest local build *.nupkg is [here](https://drive.google.com/open?id=0B4s_gXgDJAgbRDljMF9WLTNzcFU&authuser=0). Could you retry [the above steps](https://github.com/urasandesu/Prig/issues/32#issuecomment-89479093)?

**Comment by wegged** [comment] 2015-04-14 15:45
Ok one problem solved there is another method in the same class giving me issues now.  This is the stacktrace 

 	ntdll.dll!7707e753()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for ntdll.dll]	
 	ntdll.dll!7707f659()	Unknown
 	ntdll.dll!76fde023()	Unknown
>	Urasandesu.Prig.dll!0ffca699()	Unknown
 	ntdll.dll!76fcfaea()	Unknown
 	Urasandesu.Prig.dll!0ff40479()	Unknown
 	clrjit.dll!72caa00b()	Unknown
 	clrjit.dll!72c99bf5()	Unknown
 	clrjit.dll!72ca44cb()	Unknown
 	clrjit.dll!72ca087b()	Unknown
 	clrjit.dll!72ca08a0()	Unknown
 	Urasandesu.Prig.dll!0ff3cecd()	Unknown
 	Urasandesu.Prig.dll!0ff3e97a()	Unknown
 	Urasandesu.Prig.dll!0ff3d34b()	Unknown
 	[Managed to Native Transition]	
 	UnitTestProject1.dll!UnitTestProject1.UnitTest1.TestMethod4() Line 46	C#


Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	vstest.executionengine.x86.exe
  Application Version:	12.0.30501.0
  Application Timestamp:	5361ed09
  Fault Module Name:	StackHash_3850
  Fault Module Version:	6.1.7601.18247
  Fault Module Timestamp:	521ea8e7
  Exception Code:	c0000374
  Exception Offset:	000ce753
  OS Version:	6.1.7601.2.1.0.256.4
  Locale ID:	1033
  Additional Information 1:	3850
  Additional Information 2:	38507ad4ca1a60c461749906b4a1931a
  Additional Information 3:	379f
  Additional Information 4:	379f2e6d04cbd4636ecb4e9076766b08

I should also mention with the new packages I get unable to connect to test process when I run x64 as the test platform not sure why this is.

**Comment by wegged** [comment] 2015-04-14 16:24
interestingly enough I readded the assemblies to the gac (and kept the assemblies local as well) and both issues (x64 and the issue with the stub are both resolved) :dancers: !

**Comment by wegged** [comment] 2015-04-14 20:43
Spoke to soon problem came back.  I cant resolve it the same way this time.  Not sure what the issue is.

**Comment by wegged** [comment] 2015-04-15 22:33
These issues are all resolved btw everything is working now.

**Comment by urasandesu** [comment] 2015-04-16 12:10
Oh! That's great! Congratulation! :tada:

My understanding is that the remaining issue is to automate [the manual installation steps](https://github.com/urasandesu/Prig/issues/32#issuecomment-89479093).
It will be handled by Issue #33, so let me close this issue.

**Closed by urasandesu** 2015-04-16 12:10 UTC
Labels: bug
