### ISSUE TITLE
Support for Continuous Integration Server (like AppVeyor)

### ISSUE THREAD

**Issue by umaranis** [urasandesu/Prig#57] opened 2016-01-26 21:11 UTC
Could the tests written with prig run on integration servers like AppVeyor?

**Comment by urasandesu** [comment] 2016-01-28 09:14
Currently, Prig doesn't support AppVeyor, sorry. On first inspection, it seems AppVeyor doesn't provide the way to elevate administrator, but the permission is required by the design of Prig. 
You can use Prig in the CI server you managed.

**Comment by urasandesu** [comment] 2016-01-28 11:20
**MEMO**
I found [the article to run OpenCover at AppVeyor](http://www.endzone.co.uk/opencover-nunit-test-coverage-on-appveyor/). That uses unmanaged profiling API as same as Prig, so I think that there is some way to achieve also in Prig.

**Comment by urasandesu** [comment] 2016-01-30 14:59
**MEMO**
I tried to build [Prig.Samples in the AppVeyor](https://ci.appveyor.com/project/urasandesu/prig-samples). This is just in progress, but it turns out that [the above comment](https://github.com/urasandesu/Prig/issues/57#issuecomment-176077088) is my misunderstanding by the following reasons: 
* AppVeyor supports running the install script as Administrator.  
It was referenced in [this discussions](http://help.appveyor.com/discussions/questions/394-installing-a-database-from-mdf). And, I confirmed that `mklink` command can run in the install script.
* AppVeyor supports [Chocolatey](https://www.appveyor.com/docs/build-configuration#chocolatey).  
This means that we can use [Prig Chocolatey installer](https://chocolatey.org/packages/Prig/2.1.1).

Probably, we can make the sample project test runnable by just implementing the procedure same as the VSIX menu(`PRIG` - `Register Prig (Needs Restarting)`) in the install script.

**Comment by urasandesu** [comment] 2016-01-31 09:08
**MEMO**

I made [the Prig sample project succeed to build in AppVeyor](https://ci.appveyor.com/project/urasandesu/prig-samples/build/1.0.10). The following is the build script: 

[appveyor.zip](https://github.com/urasandesu/Prig/files/111185/appveyor.zip)

Unfortunately, I think this is too difficult as it is now.
I'm planning to implement the feature to satisfy this enhancement against VSIX. If it is done, user will be able to succeed their build with writing only a few line script.

**Comment by umaranis** [comment] 2016-01-31 14:53
Great news :+1: 

Looking forward to the enhancement.

**Comment by urasandesu** [comment] 2016-02-23 09:59
This issue is fixed in the following commit:
b98d7b3786080f2124b10cf4e4aeaa61f0b6dbb2

**Closed** 2016-02-23 09:59 UTC
Labels: enhancement
